---
- name: Deploying Application in Server
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Install Node.js
      shell: curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash - && sudo apt-get install -y nodejs

    - name: Install npm
      yum:
        name: npm
        state: present

    - name: Install pm2 globally
      npm:
        name: pm2
        global: yes

    - name: Install serve globally
      npm:
        name: serve
        global: yes

    - name: Create /opt/frontend directory
      file:
        path: /opt/frontend
        state: directory
        mode: 0755
      
    - name: Create /opt/BackEnd directory
      file:
        path: /opt/BackEnd
        state: directory
        mode: 0755
      
    - name: Copy frontend archive file to /opt
      copy:
        src: "/var/lib/jenkins/workspace/CI_Job/frontend/frontend-4.tar.gz"  # i have harcoded the value 4 from first job of last success build number
        dest: "/opt/frontend/frontend-4.tar.gz"
        mode: 0644

    - name: Copy backend archive file to /opt
      copy:
        src: "/var/lib/jenkins/workspace/CI_Job/BackEnd/BackEnd-4.tar.gz"    # i have harcoded the value 4 from first job of last success build number
        dest: "/opt/BackEnd/BackEnd-4.tar.gz"
        mode: 0644

    - name: Unarchive frontend
      unarchive:
        src: "/opt/frontend/frontend-4.tar.gz"
        dest: "/opt/frontend"
        remote_src: yes

    - name: Unarchive BackEnd
      unarchive:
        src: "/opt/BackEnd/BackEnd-4.tar.gz"
        dest: "/opt/BackEnd"
        remote_src: yes

    - name: Delete existing backend application process if running
      command: pm2 delete index
      ignore_errors: yes
    
    - name: Delete existing frontend application process if running
      command: pm2 delete static-page-server-3000
      ignore_errors: yes

    - name: Start backend application
      shell:
        cmd: "npm install"
        chdir: "/opt/BackEnd"
      register: npm_install_result
      ignore_errors: yes

    - name: Start backend application with pm2
      shell:
        cmd: "pm2 start index.js -f"
        chdir: "/opt/BackEnd"
      when: npm_install_result is succeeded

    - name: Start frontend application
      command: pm2 serve build 3000
      args:
        chdir: /opt/frontend
